server:
  port: 3031
  ssl:
    enabled: false
  servlet:
    context-path: /demo

spring:
  rabbitmq:
    addresses: amqp://localhost
  cloud:
    stream:
      rabbit:
        binder:
          headers: type
      bindings:
        consumerChannel:
          binder: rabbit
          destination: demo-queue
        producerChannel:
          binder: rabbit
          destination: demo-queue

  data:
    mongodb:
      uri: mongodb://localhost:27017/todo-store
